
swagger: '2.0'
schemes:
  - http
  - https
host: 54.
basePath: /api/v1/
info:
  description: |
    This is the documentation for the Doxa programming interface.
  version: 0.1.0
  title: Doxa API
  # termsOfService: 'http://swagger.io/terms/'
  # contact:
  #   email: codewiseio@gmail.com
  #   url: ...
  # x-logo:
  #   url: 'https://rebilly.github.io/ReDoc/petstore-logo.png'
  license:
    name: None
    url: ''
# externalDocs:
#   description: Add some external documents here.
#   url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: doxa
    description: Common Belief Platform
securityDefinitions:
  Bearer:
    description: |
      Authentication using JWT and the "Authorization: Bearer ..." http headers.
    type: basic
    name: Authorization
    in: header
x-servers:
  - url: //45.63.97.113:1200/v1/api
    description: Default server
  # - url: //petstore.swagger.io/sandbox
  #   description: Sandbox server
paths:
  $ref: paths.yaml
definitions:
  $ref: definitions.yaml
  

